name: Documentation

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate()
        shell: julia --project=docs/ --color=yes {0}
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
